### ISSUE TITLE
TagInfo ordering could be a float.

### ISSUE THREAD

**Issue by farodin91** [ruma/ruma-events#4]

**Comment by jimmycuadra** [comment]
Any context for this? Is there something in the spec that shows a float value for a tag ordering?

**Comment by farodin91** [comment]
The implementation in vector provide a float. 
Spec is not specific. The content must be a json object. Order is the only defined.

**Comment by jimmycuadra** [comment]
@richvdh Can you clarify here?

**Comment by richvdh** [comment]
I'm not sure I understand the question.

The spec says that the `order` property of tags is a string, which is compared lexicographically, Apparently vector does set it to a number rather than a string, which is broken, but I don't think the server needs to do anything with the content of tags anyway.

**Comment by richvdh** [comment]
(vector bug raised at https://github.com/vector-im/vector-web/issues/2476)

**Comment by jimmycuadra** [comment]
Ah, OK. We need to change it from `u64` to `String` then. Thanks!
