### ISSUE TITLE
Canonical alias content is required

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-events#97]
ruma_events::room::canonical_alias::CanonicalAliasEventContent

https://matrix.org/docs/spec/client_server/r0.6.0#m-room-canonical-alias

**Comment by timokoesters** [comment]
https://github.com/matrix-org/matrix-doc/pull/2432 could be implemented too maybe?

**Comment by jplatte** [comment]
The spec is in conflict with itself here. It says the field is required, while at the same time stating

> A room with an `m.room.canonical_alias` event with an absent, null, or empty `alias` field should be treated the same as a room with no `m.room.canonical_alias` event.

Since the current solution is the more conservative one, I think I'd rather keep it. But maybe we could get rid of the `Option` if the spec decides the `Required.` is to be kept, but the statement I quoted will be removed.

**Comment by timokoesters** [comment]
https://github.com/matrix-org/matrix-doc/pull/2432/files#diff-a9ccbaea3cb53ab4c6147d0a7e7f10c2R85
